concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  MAVEN_OPTS: -Xss1500k -Xmx1500m -Daether.connector.http.reuseConnections=false -Daether.connector.requestTimeout=60000
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true
    -Dmaven.wagon.http.serviceUnavailableRetryStrategy.class=standard -Dmaven.wagon.rto=60000
jobs:
  backward-compatibility-tests:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: Backward compatibility tests
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Clean Disk
      uses: ./.github/actions/clean-disk
      with:
        mode: full
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Pick ubuntu mirror for the docker image build
      run: '# pick the closest ubuntu mirror and set it to UBUNTU_MIRROR environment
        variable

        $GITHUB_WORKSPACE/dev/ci-tool pick_ubuntu_mirror

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -nsu clean install -Pdocker -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
    - continue-on-error: true
      name: Test current server with old clients
      run: mvn -B -nsu -DbackwardCompatTests -pl :backward-compat-current-server-old-clients
        test
    - continue-on-error: true
      name: Test progressive upgrade
      run: mvn -B -nsu -DbackwardCompatTests -pl :upgrade test
    - continue-on-error: true
      name: Other tests
      run: 'mvn -B -nsu -DbackwardCompatTests -pl :bc-non-fips,:hierarchical-ledger-manager,:hostname-bookieid,:old-cookie-new-cluster,:recovery-no-password,:upgrade-direct,:yahoo-custom-version
        test

        '
    - continue-on-error: true
      if: ${{ !success() }}
      name: Upload container logs on failure
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: backward-compatibility-tests-container-logs
        path: '**/docker.log

          '
        retention-days: 7
    - continue-on-error: true
      if: ${{ always() }}
      name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
      uses: ./.github/actions/copy-test-reports
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: apache/pulsar-test-infra/action-junit-report@master
      with:
        annotate_only: 'true'
        report_paths: surefire-reports/TEST-*.xml
    - continue-on-error: true
      if: failure()
      name: Upload Surefire reports
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: backward-compatibility-tests-reports
        path: surefire-reports
        retention-days: 7
    timeout-minutes: 75
  build-and-license-check:
    name: PR Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: changes
      name: Detect changed files
      uses: apache/pulsar-test-infra/paths-filter@master
      with:
        filters: .github/changes-filter.yaml
        list-files: csv
    - continue-on-error: true
      id: check_changes
      name: Check changed files
      run: 'echo "docs_only=${{ fromJSON(steps.changes.outputs.all_count) == fromJSON(steps.changes.outputs.docs_count)
        && fromJSON(steps.changes.outputs.docs_count) > 0 }}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: cache
      if: steps.check_changes.outputs.docs_only != 'true'
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      if: steps.check_changes.outputs.docs_only != 'true'
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      if: steps.check_changes.outputs.docs_only != 'true'
      name: Validate pull request
      run: 'mvn -T 1C -B -nsu clean install -Ddistributedlog -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

        mvn -T 1C -B -nsu apache-rat:check checkstyle:check spotbugs:check package
        -Ddistributedlog -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

        '
    - continue-on-error: true
      if: steps.check_changes.outputs.docs_only != 'true'
      name: Check license files
      run: dev/check-all-licenses
    - continue-on-error: true
      if: steps.check_changes.outputs.docs_only != 'true'
      name: Generate Javadoc
      run: mvn -B -nsu -am -pl bookkeeper-common,bookkeeper-server,:bookkeeper-stats-api,:bookkeeper-stats-providers,:codahale-metrics-provider,:prometheus-metrics-provider
        javadoc:aggregate -DskipTests -Pdelombok -Dchesktyle.skip -Dspotbugs.skip
    timeout-minutes: 60
  integration-tests:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: Integration Tests
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Clean Disk
      uses: ./.github/actions/clean-disk
      with:
        mode: full
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Pick ubuntu mirror for the docker image build
      run: '# pick the closest ubuntu mirror and set it to UBUNTU_MIRROR environment
        variable

        $GITHUB_WORKSPACE/dev/ci-tool pick_ubuntu_mirror

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -nsu clean install -Pdocker -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
    - continue-on-error: true
      name: Run metadata driver tests
      run: mvn -B -nsu -f metadata-drivers/pom.xml test -DintegrationTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
    - continue-on-error: true
      name: Run all integration tests (except backward compatibility tests)
      run: 'mvn -B -nsu -f tests/pom.xml test -DintegrationTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        -DredirectTestOutputToFile=false -DtestRetryCount=0

        '
    - continue-on-error: true
      if: cancelled()
      name: print JVM thread dumps when cancelled
      run: ./dev/ci-tool print_thread_dumps
    - continue-on-error: true
      if: ${{ !success() }}
      name: Upload container logs on failure
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: integration-tests-container-logs
        path: '**/docker.log

          '
        retention-days: 7
    - continue-on-error: true
      if: ${{ always() }}
      name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
      uses: ./.github/actions/copy-test-reports
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: apache/pulsar-test-infra/action-junit-report@master
      with:
        annotate_only: 'true'
        report_paths: surefire-reports/TEST-*.xml
    - continue-on-error: true
      if: failure()
      name: Upload Surefire reports
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: integration-tests-reports
        path: surefire-reports
        retention-days: 7
    timeout-minutes: 75
  jdk-compatibility-checks:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: ${{ matrix.step_name }}
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk_version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package -B -nsu -DskipBookKeeperServerTests -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
    - continue-on-error: true
      if: cancelled()
      name: print JVM thread dumps when cancelled
      run: ./dev/ci-tool print_thread_dumps
    strategy:
      fail-fast: false
      matrix:
        include:
        - jdk_version: 8
          step_name: Compatibility Check Java8
        - jdk_version: 11
          step_name: Compatibility Check Java11
        - jdk_version: 17
          step_name: Compatibility Check Java17
    timeout-minutes: ${{ matrix.timeout || 60 }}
  macos-build:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: Build with macos on JDK 11
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: mvn package
      run: mvn -B -nsu clean package -DskipTests
    timeout-minutes: 30
  owasp-dependency-check:
    if: ${{ needs.build-and-license-check.outputs.need_owasp == 'true' }}
    name: OWASP Dependency Check
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      name: Set up Maven
      uses: apache/pulsar-test-infra/setup-maven@master
      with:
        maven-version: 3.8.7
    - continue-on-error: true
      name: run "clean install verify" to trigger dependency check
      run: mvn -q -B -ntp clean install verify -Powasp-dependency-check -DskipTests
        -pl '!stream/distributedlog/io/dlfs'
    - continue-on-error: true
      if: ${{ cancelled() || failure() }}
      name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: dependency report
        path: target/dependency-check-report.html
        retention-days: 7
    timeout-minutes: 60
  unit-tests:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: ${{ matrix.step_name }}
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build
      run: "projects_list=\nif [[ ! -z \"${{ matrix.module }}\" ]]; then\n  projects_list=\"\
        -pl ${{ matrix.module }}\"\nfi\nmvn -q -T 1C -B -nsu $projects_list install\
        \ -am -DskipTests -Dcheckstyle.skip -Dspotbugs.skip -Drat.skip -Dmaven.javadoc.skip\n"
    - continue-on-error: true
      name: Test - ${{ matrix.step_name }}
      run: "projects_list=\nif [[ ! -z \"${{ matrix.module }}\" ]]; then\n  projects_list=\"\
        -pl ${{ matrix.module }}\"\nfi\nmvn -B -nsu $projects_list verify ${{ matrix.test_args\
        \ }}\n"
    - continue-on-error: true
      if: ${{ always() }}
      name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
      uses: ./.github/actions/copy-test-reports
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: apache/pulsar-test-infra/action-junit-report@master
      with:
        annotate_only: 'true'
        report_paths: surefire-reports/TEST-*.xml
    - continue-on-error: true
      if: failure()
      name: Upload Surefire reports
      uses: actions/upload-artifact@v4
      with:
        name: unit-${{ matrix.step_name }}-reports
        path: surefire-reports
        retention-days: 7
    - continue-on-error: true
      if: cancelled()
      name: print JVM thread dumps when cancelled
      run: ./dev/ci-tool print_thread_dumps
    strategy:
      fail-fast: false
      matrix:
        include:
        - flag: bookie
          module: bookkeeper-server
          step_name: Bookie Tests
          test_args: -Dtest='org.apache.bookkeeper.bookie.**'
        - flag: client
          module: bookkeeper-server
          step_name: Client Tests
          test_args: -Dtest='org.apache.bookkeeper.client.**'
          timeout: 75
        - flag: replication
          module: bookkeeper-server
          step_name: Replication Tests
          test_args: -Dtest='org.apache.bookkeeper.replication.**'
        - flag: remaining
          module: bookkeeper-server
          step_name: Remaining Tests
          test_args: -Dtest='!org.apache.bookkeeper.client.**,!org.apache.bookkeeper.bookie.**,!org.apache.bookkeeper.replication.**,!org.apache.bookkeeper.tls.**'
        - flag: tls
          module: bookkeeper-server
          step_name: TLS Tests
          test_args: -Dtest='org.apache.bookkeeper.tls.**'
        - flag: stream
          step_name: StreamStorage Tests
          test_args: -f stream/pom.xml -DstreamTests
        - flag: shell
          module: tests/scripts
          step_name: Shell tests
    timeout-minutes: ${{ matrix.timeout || 60 }}
  windows-build:
    if: ${{ needs.build-and-license-check.outputs.docs_only != 'true' }}
    name: Build with windows on JDK 11
    needs:
    - build-and-license-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Install mingw
      run: choco install mingw
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: mvn package
      run: mvn -B -nsu clean package -DskipTests
    timeout-minutes: 30
name: BookKeeper CI
on:
  repository_dispatch:
    types: trigger-ga___bk-ci.yml
