jobs:
  Stream-storage-python-client-integration-tests:
    name: StreamStorage Python Client Integration Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      id: cache
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/*/*/*

          !~/.m2/repository/org/apache/bookkeeper

          !~/.m2/repository/org/apache/distributedlog

          '
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build
      run: mvn -q -T 1C -B -nsu clean install -DskipTests -Dcheckstyle.skip -Dspotbugs.skip
        -Drat.skip -Dmaven.javadoc.skip
    - continue-on-error: true
      name: Pick ubuntu mirror for the docker image build
      run: '# pick the closest ubuntu mirror and set it to UBUNTU_MIRROR environment
        variable

        $GITHUB_WORKSPACE/dev/ci-tool pick_ubuntu_mirror

        '
    - continue-on-error: true
      name: Build Test image
      run: ./stream/clients/python/docker/build-local-image.sh
    - continue-on-error: true
      name: Test
      run: ./stream/clients/python/scripts/docker_integration_tests.sh
    timeout-minutes: 60
  stream-storage-python-client-unit-tests:
    name: StreamStorage Python Client Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Test
      run: ./stream/clients/python/scripts/test.sh
    timeout-minutes: 60
name: BookKeeper StreamStorage Python Client
on:
  repository_dispatch:
    types: trigger-ga___bk-streamstorage-python.yml
