jobs:
  bot:
    name: Bot tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: clone repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        PROVIDER: apache
        REPOSITORY: bookkeeper
        RERUN_CMD: rerun failure checks
      name: bot actions
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.BKBOT_TOKEN}}
        script: 'const path = require(''path'')

          const scriptPath = path.resolve(''.github/actions/bot/src/run.js'')

          require(scriptPath)({core}, {context}, {github})'
name: Bot tests
on:
  repository_dispatch:
    types: trigger-ga___bot.yml
