concurrency:
  cancel-in-progress: true
  group: dlc-${{ github.event.pull_request.number || github.ref }}
jobs:
  check-dead-links:
    name: Dead link checker
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      run: sudo npm install -g markdown-link-check@3.11.2
    - continue-on-error: true
      run: "for file in $(find . -name \"*.md\"); do\n  markdown-link-check -c .dlc.json\
        \ -q \"$file\"\ndone"
    timeout-minutes: 30
name: Dead link checker
on:
  repository_dispatch:
    types: trigger-ga___dead-link-checker.yaml
