jobs:
  website-pull-validation:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - continue-on-error: true
      name: Setup yarn
      run: npm install -g yarn
    - continue-on-error: true
      name: Build website
      run: './site3/website/scripts/build-website.sh

        '
    timeout-minutes: 60
name: Website PR validation
on:
  repository_dispatch:
    types: trigger-ga___website-pr-validation.yml
